apiVersion: v1
kind: ConfigMap
metadata:
  name: csvserver-input
data:
  inputdata: |
    0, 20970
    1, 25257
    2, 30188
    3, 23844
    4, 1407
    5, 30192
    6, 28077
    7, 5285
    8, 28197
    9, 17778   